debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
               permanent=true
               regex = "^http://www.(.*)"
               replacement = "http://$1"
        entryPoint = "https"

    [entryPoints.https]
    address = ":443"
        [entryPoints.https.redirect]
               permanent=true
               regex = "^https://www.(.*)"
               replacement = "https://$1"
        [entryPoints.https.tls]

# dashboard traefik
    [entryPoints.dashboard]
    address = ":8080"

[api]
entryPoint = "dashboard"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
# domena
domain = "zespolarto.pl"
watch = true
exposedByDefault = false

[acme]
email = "admins@edulab.io"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
